# Algorithm Configuration
# Settings for RRT* and other planning algorithms

planning:
  # RRT* Parameters  
  rrt_star:
    step_size: 0.8  # meters - balanced for speed and quality
    max_iterations: 15000  # Increased for difficult cases  
    goal_threshold: 0.5  # meters - reasonable accuracy
    search_radius: 2.5  # meters for rewiring
    goal_sample_rate: 0.25  # probability of sampling goal - balanced
    
  # Environment-specific overrides
  env_overrides:
    shopping_mall:
      max_iterations: 30000  # Large space - balanced for performance
      step_size: 1.2  # Larger steps for open space
      goal_sample_rate: 0.35  # Moderate goal bias
    maze:
      max_iterations: 35000  # Complex maze - high but reasonable
      step_size: 0.3  # Small steps for narrow passages
      goal_sample_rate: 0.55  # High goal bias
    track:
      max_iterations: 20000  # U-shaped track
      step_size: 0.35  # Small steps for narrow track
      goal_sample_rate: 0.45  # High goal bias
    narrow_graph:
      step_size: 0.5  # Small steps for acute angles
      max_iterations: 15000
    office02:
      max_iterations: 25000  # Large office
      step_size: 0.6  # Balanced steps
      goal_sample_rate: 0.4  # Moderate goal bias
    
  # Robot motion parameters
  motion:
    max_velocity: 0.5  # m/s - robot max speed
    dt: 0.1  # seconds - time step for simulation
    
  # Safety parameters  
  safety:
    min_obstacle_distance: 0.3  # meters - minimum safe distance
    collision_check_resolution: 0.05  # meters - resolution for path collision checking
    
  # Path optimization
  optimization:
    smooth_path: false
    smoothing_iterations: 10
    smoothing_weight: 0.5

# Experiment execution settings
experiments:
  # Which methods to compare
  methods_to_test:
    - naive
    - standard_cp
    - learnable_cp
    
  # Which environments to test
  test_environments:
    - office01add
    - office02
    - shopping_mall
    - room02
    - maze
    - track
    - narrow_graph
    
  # Output settings
  output:
    save_paths: true
    save_visualizations: true
    generate_report: true
    verbose: true